### ISSUE TITLE
能否提供下数据转bin 文件和各个阶段的训练脚本？

### ISSUE THREAD

**Issue by canghaiyunfan** [multimodal-art-projection/MAP-NEO#19]
感谢作者开源数据和代码，目前开源内容没法复现，请问是否可以开源数据转bin以及各个阶段的训练脚本

**Comment by xingweiqu** [comment]
可以看一下，Megatron-LM-NEO, 里面follow megatron的方法，先做preprocess，然后 训练脚本也可以看见都在neo里面
