### ISSUE TITLE
similar_line_dedup代码实现和论文中的描述不一致

### ISSUE THREAD

**Issue by lylcst** [multimodal-art-projection/MAP-NEO#30]
代码中的实现：
![image](https://github.com/multimodal-art-projection/MAP-NEO/assets/85541451/f34c861f-9a39-4aad-8022-09eb6727e20e)

论文中的描述：
<img width="943" alt="image" src="https://github.com/multimodal-art-projection/MAP-NEO/assets/85541451/4b7827b4-b042-42a8-9366-2d5190e0243c">

代码中取得是两行的最大长度，而论文中描述是那个短的长度

**Comment by panDing19** [comment]
Thank you for your correction. The issue was indeed due to code implementation. We will correct the errors in the next version of the paper.
